from typing import List, AsyncGenerator, Optional

class ResponseChunker:
    """
    Buffers text tokens generated by the LLM reasoning backend and yields sentences
    or word chunks adaptively based on punctuation or length constraints.
    """
    def __init__(self, max_tokens: int = 15):
        self.max_tokens = max_tokens
        self.buffer: List[str] = []
        self.token_count = 0

    async def feed(self, token: str) -> AsyncGenerator[str, None]:
        """
        Appends a token to the buffer. If sentence endings (. ! ?) or the maximum 
        token threshold is met, flushes and yields the compiled chunk.
        """
        self.buffer.append(token)
        self.token_count += 1

        stripped = token.strip()
        is_terminal = False
        if stripped:
            is_terminal = stripped[-1] in ('.', '?', '!')

        if is_terminal or self.token_count >= self.max_tokens:
            chunk = self.flush()
            if chunk:
                yield chunk

    def flush(self) -> str:
        """
        Clears the buffer and returns any remaining text.
        """
        if not self.buffer:
            return ""
        chunk = "".join(self.buffer).strip()
        self.buffer = []
        self.token_count = 0
        return chunk
